import { StyleSheet } from 'react-native';
import { COLORS } from '../../colors';

export default StyleSheet.create({
	container: {
		flex: 1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: COLORS.primary,
	},
	card: {
		backgroundColor: COLORS.lightBackground,
		padding: 32, 
		borderRadius: 10,
		alignItems: 'center',
		elevation: 4, 
		shadowColor: '#000', 
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.1,
		shadowRadius: 10,
		width: 320, 
	},
	logo: {
		width: 160, 
		height: 160,
		resizeMode: 'contain',
		marginBottom: 16,
	},
	cardText: {
		marginVertical: 8, 
		marginTop: 24, 
		color: COLORS.text,
		fontSize: 16,
		textAlign: 'center',
	},
	picker: {
		width: '100%',
		height: 44,
		padding: 0,
		marginVertical: 10, 
		borderWidth: 1,
		borderColor: '#ccc',
		borderRadius: 5,
		backgroundColor: COLORS.lightBackground, 
	},
	input: {
		width: '100%',
		padding: 10, 
		marginVertical: 10, 
		borderWidth: 1,
		borderColor: '#ccc',
		borderRadius: 5,
		backgroundColor: COLORS.lightBackground, 
	},
	button: {
		width: '100%',
		backgroundColor: COLORS.primary,
		padding: 12,
		borderRadius: 6,
		alignItems: 'center',
		marginTop: 8,
		marginBottom: 8,
	},
	buttonText: {
		color: COLORS.white,
		fontWeight: 'bold',
		fontSize: 16,
	},
	link: {
		color: COLORS.info,
		marginTop: 8,
		textDecorationLine: 'underline',
	},
});
